updated

diff --git a/.github/workflows/final.yaml b/.github/workflows/final.yaml
--- a/.github/workflows/final.yaml
+++ b/.github/workflows/final.yaml
@@ -161,11 +161,11 @@ jobs:
       run: |
         IMG="$QUAR_IMAGE_REGISTRY/$REPO_NAME:insecure-$COMMIT_TAG"
 
-        # Check if the image exists
-        if ! gcloud artifacts docker images describe "$IMG" --location=$GAR_LOCATION >/dev/null 2>&1; then
-          echo "::error::Image $IMG not found in $GAR_LOCATION"
-          exit 1
-        fi
+        # # Check if the image exists
+        # if ! gcloud artifacts docker images describe "$IMG" --location=$GAR_LOCATION >/dev/null 2>&1; then
+        #   echo "::error::Image $IMG not found in $GAR_LOCATION"
+        #   exit 1
+        # fi
 
         # Initiate a new scan
         SCAN_RESULT=$(gcloud artifacts docker images scan "$IMG" --location=us --format="value(response.scan)")
